name: Production Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/*'
      - 'README.md'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'

jobs:
  Deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g hexo-cli
      - run: npm install

      - name: Generate Hexo
        run: hexo generate

      - name: Copy Additional Files
        run: cp -rf files/* public/

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: /wbx.gg/
